#!/bin/bash

# achoovariables - Variables for the Achoo! Arch Linux Installation Script
# ------------------------------------------------------------------------
# This script and the achoofuncs script must be present in the same directory
# when running the main Achoo! script

# Developed by Elizabeth Mills, incorporating some code adapted from
# the Evo/Lution script by Carl Duff and the AUI scripts by HelmuthDU.

# ------------------------------------------------------
# Please read the introduction in the main Achoo! script
# ------------------------------------------------------

# -------------------
# Partition variables
# -------------------
declare -a AddPartList	# Array of additional partitions by system name. eg: /dev/sda5
declare -a AddPartLabel # Array of labels for the same partitions in the same order. eg: /home
declare -a AddPartType	# Array of format type for the same partitions. eg: ext4
GrubDevice=""     # "/dev/sda"
SwapPartition=""  # "/dev/sda2"
SwapFile=""       # "2G"
RootPartition=""  # "/dev/sda1"
RootType=""       # "ext4"
Partition=""      # "sda1"
PartitionListBeforeRoot=""   # For reviewing partitions
PartitionListBeforeSwap=""   # For reviewing partitions
PartitionListBeforeExtras="" # For reviewing partitions
MOUNTPOINT="/mnt"

# ------------------
# Location variables
# ------------------
CountryCode=""    # "GB" Country code for mirrorlist
CountryLocale=""  # "en_GB.UTF-8"	Locale
Countrykbd=""     # "uk" keyboard
ZONE=""           # "Europe" For time
SUBZONE=""        # "London" For time

# ----------------------------------------------------------
# Desktop environment, display manager and greeter variables
# ----------------------------------------------------------
DesktopEnvironment=""  # "xfce4"
DisplayManager=""      # "lightdm"
Greeter=""             # "lightdm-gtk-greeter" # Not required for some DMs

# -----------------------
# Root and user variables
# -----------------------
HostName=""       # "ArchLinux"
RootPassword=""   # "Root"
UserName=""       # "archie"
UserPassword=""   # "Linux"

# ----------------------
# Input/Output variables
# ----------------------
OutPrompt="Press [Enter] to continue."
AnyPrompt="Press any key to continue."
prompt1="Enter the number of your selection : "
Response="" # Global user input variable
Banner="~ https://wiki.archlinux.org ~"
