#!/bin/bash

# achoovariables - Variables called by the main Achoo! script
# -----------------------------------------------------------
# This script and the achoofuncs script must be present in the same 
# directory when running the main Achoo! script
# -----------------------------------------------------------
# Developed by Elizabeth Mills, incorporating some code adapted from
# the Evo/Lution script by Carl Duff and the AUI scripts by HelmuthDU.
# -----------------------------------------------------------
# Please read the introduction in the main Achoo! script
# ------------------------------------------------------

#
# Partition variables
#
declare -a AddPartList	# Array of additional partitions by system name. eg: /dev/sda5
declare -a AddPartLabel # Array of labels for the same partitions in the same order. eg: /home
declare -a AddPartType	# Array of format type for the same partitions. eg: ext4
GrubDevice=""     # "/dev/sda"
SwapPartition=""  # "/dev/sda3"
FormatSwap="N"    # User selects whether to reuse swap
SwapFile=""       # "2G"
IsSwap=""         # Result of lsblk test
RootPartition=""  # "/dev/sda2"
RootType=""       # "ext4"
Partition=""      # "sda1"
DualBoot="N"      # Ready for dual-booting option
EFIPartition=""   # Will hold partition label for mounting
AutoPart=0        # Flag - changes to 1 if auto-partition is chosen
UseDisk="sda"     # Used if more than one disk
DiskDetails=0     # Size of selected disk

#
# Location variables
#
CountryCode=""    # "GB" Country code for mirrorlist
CountryLocale=""  # "en_GB.UTF-8"	Locale
Countrykbd=""     # "uk" keyboard
ZONE=""           # "Europe" For time
SUBZONE=""        # "London" For time
#
# Desktop environment, display manager and greeter variables
#
DesktopEnvironment=""  # "xfce4"
GoodiesXfce=""
GoodiesGnome=""
GoodiesOpenbox=""
DisplayManager=""      # "lightdm"
Greeter=""             # "lightdm-gtk-greeter" (Not required for some DMs)
#
# Root and user variables
#
HostName=""       # "arch-linux"
UserName=""       # "archie"
Scope="Basic"     # Installation scope ... 'Extras' 'Full' or 'Basic'
#
# Input/Output variables
#
OutPrompt="Press [Enter] to continue."
AnyPrompt="Press any key to continue."
prompt1="Enter the number of your selection : "
Response="" # Global user input variable
Banner="~ https://wiki.archlinux.org ~"
