#!/bin/bash

# The Feliz2 installation scripts for Arch Linux
# Developed by Elizabeth Mills
# Revision date: 15th October 2016

# Please read the introduction in the README file
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# A copy of the GNU General Public License is available from the Feliz2
# page at http://sourceforge.net/projects/feliz2/files
# or https://github.com/angeltoast/feliz2, or write to:
# The Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# In this module: functions used during installation
# -------------------------      -------------------------
# Functions           Line       Functions           Line
# -------------------------      -------------------------
# arch_chroot           36       ReflectorMirrorList  190
# Parted                41
# TPecho                45       LocalMirrorList      200
# read_timed            63       InstallDM            215
# MountPartitions       76       InstallLuxuries      225
# InstallKernel        157       UserAdd              325
# AddCodecs            166       SetRootPassword      340
# McInitCPIO           181       SetUserPassword      378
# -------------------------      -------------------------

arch_chroot() {  # From Lution AIS
  arch-chroot /mnt /bin/bash -c "${1}" 2>> feliz.log
}

Parted() {
  parted --script /dev/${UseDisk} "$1" 2>> feliz.log
}

TPecho() { # For displaying status while running on auto
  echo
  CurrentTime=$(date +%s)
  Difference=$(( $CurrentTime-$StartTime ))
  DIFFMIN=$(( $Difference/60 ))
  DIFFSEC=$(( $Difference % 60 ))
  T_COLS=`tput cols`
  EMPTY="     "
  lov=${#1}
  if [ ${lov} -lt ${T_COLS} ]; then
    stpt=$(( ($T_COLS - $lov) / 3 ))
    EMPTY="$(printf '%*s' $stpt)"
  fi
  tput bold
  echo -e "$EMPTY $1 \n"
  tput sgr0
}

read_timed() { # Timed display - $1 = text to display; $2 = duration
  T_COLS=`tput cols`
  lov=${#1}
  if [ $2 ]; then
    tim=$2
  else
    tim=2
  fi
  if [ ${lov} -lt ${T_COLS} ]; then
    stpt=$(( ($T_COLS - $lov) / 2 ))
    EMPTY="$(printf '%*s' $stpt)"
  else
    EMPTY=""
  fi
  read -t ${tim} -p "$EMPTY $1"
  echo
}

MountPartitions() {
  TPecho "Preparing and mounting partitions" ""
  
  # First unmount any mounted partitions
  umount ${RootPartition} /mnt >/dev/null 2>> feliz.log # eg: umount /dev/sda1 /mnt
  # 1) Root partition  
  case $RootType in
  "") echo "Not formatting root partition" >> feliz.log   # If /root filetype not set - do nothing
  ;;
  *) # Otherwise, check if replacing existing ext3/4 /root partition with btrfs
    CurrentType=$(file -sL ${RootPartition} | grep 'ext\|btrfs' | cut -c26-30) 2>> feliz.log
    # Check if /root type or existing partition are btrfs ...
    if [ ${CurrentType} ] && [ $RootType = "btrfs" ] && [ ${CurrentType} != "btrfs" ]; then
      btrfs-convert ${RootPartition} 2>> feliz.log      # Convert existing partition to btrfs
    elif [ $RootType = "btrfs" ]; then                  # Otherwise, for btrfs /root
      mkfs.btrfs -f ${RootPartition} 2>> feliz.log      # eg: mkfs.btrfs -f /dev/sda2
    else                                                # /root is not btrfs
      Partition=${RootPartition: -4}                    # Last 4 characters (eg: sda1)
      Label="${LabellingArray[${Partition}]}"           # Check to see if it has a label
      if [ -n "${Label}" ]; then                        # If it has a label ...
        Label="-L ${Label}"                             # ... prepare to use it
      fi
      mke2fs ${Label} -t ${RootType} ${RootPartition} &>> feliz.log
    fi                                                  # eg: mke2fs -L Arch-Root -t ext4 /dev/sda1
  esac
  mount ${RootPartition} /mnt &>> feliz.log             # eg: mount /dev/sda1 /mnt
  
  # 2) EFI (if required)
  if [ ${UEFI} -eq 1 ] && [ ${DualBoot} = "N" ]; then   # Check if EFI /boot partition required
    mkfs.fat -F32 ${EFIPartition} 2> error.log          # Format EFI boot partition
    mkdir /mnt/boot                                     # Make mountpoint
    mount ${EFIPartition} /mnt/boot                     # Mount it
  fi
  
  # 3) Swap
  if [ ${SwapPartition} ]; then
    swapoff -a 2>> feliz.log                            # Make sure any existing swap cleared
    if [ $MakeSwap = "Y" ]; then
      Partition=${SwapPartition: -4}                    # Last 4 characters (eg: sda2)
      Label="${LabellingArray[${Partition}]}"           # Check for label
      if [ -n "${Label}" ]; then
        Label="-L ${Label}"                             # Prepare label
      fi
      mkswap ${Label} ${SwapPartition} 2>> feliz.log    # eg: mkswap -L Arch-Swap /dev/sda2
    fi
    swapon ${SwapPartition} 2>> feliz.log               # eg: swapon /dev/sda2
  fi

  if [ ${SwapFile} ]; then
    fallocate -l ${SwapFile} /mnt/swapfile >/dev/null 2>> feliz.log
    chmod 600 /mnt/swapfile >/dev/null 2>> feliz.log 
    mkswap /mnt/swapfile >/dev/null 2>> feliz.log
    swapon /mnt/swapfile >/dev/null 2>> feliz.log
    # echo "/swapfile none  swap  defaults  0 0" >> /mnt/etc/fstab 2>> feliz.log
  fi

  # 4) Any additional partitions (from the related arrays AddPartList, AddPartMount & AddPartType)
  local Counter=0
  for id in ${AddPartList}                              # $id will be in the form /dev/sda2
  do
    umount ${id} /mnt${AddPartMount[$Counter]} >/dev/null 2>> feliz.log
    mkdir -p /mnt${AddPartMount[$Counter]} 2>> feliz.log  # eg: mkdir -p /mnt/home
    # Check if replacing existing ext3/4 partition with btrfs (as with /root)
    CurrentType=$(file -sL ${AddPartType[$Counter]} | grep 'ext\|btrfs' | cut -c26-30) 2>> feliz.log
    if [ ${AddPartType[$Counter]} = "btrfs" ] && [ ${CurrentType} != "btrfs" ]; then
      btrfs-convert ${id} 2>> feliz.log
    elif [ ${AddPartType[$Counter]} = "btrfs" ]; then
      mkfs.btrfs -f ${id} 2>> feliz.log &>> feliz.log   # eg: mkfs.btrfs -f /dev/sda2
    elif [ ${AddPartType[$Counter]} != "" ]; then
      Partition=${id: -4}                               # Last 4 characters of ${id}
      Label="${LabellingArray[${Partition}]}"
      if [ -n "${Label}" ]; then
        Label="-L ${Label}"                             # Prepare label
      fi
      mke2fs ${Label} -t ${AddPartType[$Counter]} ${id} &>> feliz.log # eg: mke2fs -L Arch-Home -t ext4 /dev/sda3
    fi
    mount ${id} /mnt${AddPartMount[$Counter]} &>> feliz.log # eg: mount /dev/sda3 /mnt/home
    Counter=$((Counter+1))
  done
}

InstallKernel() {   # Selected kernel and some other core systems
  case $Kernel in
  1) TPecho "Installing LTS kernel and core systems"
    # This is the full linux group list at 13th October 2016 with linux-lts in place of linux
    pacstrap /mnt autoconf automake bash binutils bison bzip2 coreutils cryptsetup device-mapper dhcpcd diffutils e2fsprogs fakeroot file filesystem findutils flex gawk gcc gcc-libs libtool gettext glibc grep groff gzip inetutils iproute2 iputils jfsutils less licenses linux-lts logrotate lvm2 m4 make man-db man-pages mdadm nano netctl pacman patch pciutils pcmciautils perl pkg-config procps-ng psmisc reiserfsprogs s-nail sed shadow sudo sysfsutils systemd-sysvcompat tar texinfo usbutils util-linux vi which xfsprogs 2>> feliz.log
  ;;
  *) TPecho "Installing Latest kernel and core systems"
    pacstrap /mnt base base-devel 2>> feliz.log
  esac

  TPecho "Installing cli tools"
  pacstrap /mnt btrfs-progs gamin gksu gvfs ntp wget openssh screenfetch unrar unzip vim xarchiver xorg-xedit xterm 2>> feliz.log

  # Enable sshd
  arch_chroot "systemctl enable sshd.service" >/dev/null

}

AddCodecs() {
  TPecho "Adding codecs"
  pacstrap /mnt a52dec autofs faac faad2 flac lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 gstreamer0.10-plugins pulseaudio pulseaudio-alsa libdvdcss dvd+rw-tools dvdauthor dvgrab flashplugin 2>> feliz.log
  
  TPecho "Installing Wireless Tools"
  pacstrap /mnt b43-fwcutter ipw2100-fw ipw2200-fw zd1211-firmware 2>> feliz.log
  pacstrap /mnt iw wireless_tools wpa_supplicant 2>> feliz.log

  TPecho "Installing X, Graphics, etc"
  pacstrap /mnt xorg-server xorg-server-utils xorg-xinit xorg-twm 2>> feliz.log
  
  TPecho "Installing  opensource video drivers"
  pacstrap /mnt xf86-video-vesa xf86-video-nouveau xf86-input-synaptics 2>> feliz.log
}

McInitCPIO() {
  case $Kernel in
  1) TPecho "Running mkinitcpio for lts kernel" 10
    arch_chroot "mkinitcpio -p linux-lts" 2>> feliz.log
  ;;
  *) TPecho "Running mkinitcpio for latest kernel" 10
    arch_chroot "mkinitcpio -p linux" 2>> feliz.log
  esac
}

ReflectorMirrorList() { # Use reflector (added to archiso) to generate fast mirror list
  TPecho "Generating mirrorlist"
  reflector --verbose -l 5 --sort rate --save /etc/pacman.d/mirrorlist 2>> feliz.log
  if [ $? -gt 0 ]; then
    LocalMirrorList
  else
    chmod +r /etc/pacman.d/mirrorlist 2>> feliz.log
  fi
}

LocalMirrorList() { # In case Reflector fails, generate and save a shortened
  # mirrorlist of only the mirrors defined in the CountryCode variable.
  URL="https://www.archlinux.org/mirrorlist/?country=${CountryCode}&use_mirror_status=on"
  MirrorTemp=$(mktemp --suffix=-mirrorlist) 2>> feliz.log
  # Use curl to get list of mirrors from the Arch mirrorlist ${URL} to ${MirrorTemp}
  curl -so ${MirrorTemp} ${URL} 2>> feliz.log
  # Use sed to filter entries
  sed -i 's/^#Server/Server/g' ${MirrorTemp} 2>> feliz.log
  # Make a safe copy of existing mirrorlist
  mv -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.orig 2>> feliz.log
  # Replace existing mirrorlist with new local mirrorlist
  mv -f ${MirrorTemp} /etc/pacman.d/mirrorlist 2>> feliz.log
  chmod +r /etc/pacman.d/mirrorlist 2>> feliz.log
}

InstallDM()
{ # Display manager
  # Disable any existing display manager
  arch_chroot "systemctl disable display-manager.service" >/dev/null
  # Then install selected display manager
  TPecho "Installing ${DisplayManager} display manager" 20
  pacstrap /mnt ${DisplayManager} ${Greeter} 2>> feliz.log
  arch_chroot "systemctl -f enable ${DisplayManager}.service" >/dev/null
}

InstallLuxuries()
{ # Install desktops and other extras
  # Display manager - runs only once
  InstallDM                  # Clear any pre-existing DM and install this one
  # First parse through LuxuriesList - checking for DEs
  if [ -n "${LuxuriesList}" ]; then
    for i in ${LuxuriesList}
    do
      case $i in
      "Budgie") TPecho "Installing the Budgie desktop Environment"
          pacstrap /mnt budgie-desktop 2>> feliz.log
        ;;
      "Cinnamon") TPecho "Installing the Cinnamon desktop Environment"
          pacstrap /mnt cinnamon 2>> feliz.log
        ;;
      "Deepin") TPecho "Installing the Deepin desktop Environment"
          pacstrap /mnt deepin 2>> feliz.log
          TPecho "Installing the Deepin extras package"
          pacstrap /mnt deepin-extra 2>> feliz.log
          # Change the greeter line in lightdm.conf
          if [ -d /mnt/etc/lightdm ]; then
            sed -i s/#greeter-session=example-gtk-gnome/greeter-session=lightdm-deepin-greeter/g /mnt/etc/lightdm/lightdm.conf 2>> feliz.log
          fi
        ;;
      "Enlightenment") TPecho "Installing the Enlightenment desktop Environment"
          pacstrap /mnt enlightenment connman terminology 2>> feliz.log
        ;;
      "Fluxbox") TPecho "Installing the Fluxbox window manager"
          pacstrap /mnt fluxbox 2>> feliz.log
        ;;
      "Gnome") TPecho "Installing the Gnome desktop Environment"
          pacstrap /mnt gnome 2>> feliz.log
          TPecho "Installing the Gnome extras package"
          pacstrap /mnt gnome-extra 2>> feliz.log
        ;;
      "KDE") TPecho "Installing the KDE Plasma meta package"
          pacstrap /mnt plasma-meta 2>> feliz.log
          TPecho "Installing the KDE applications package"
          pacstrap /mnt kde-applications 2>> feliz.log
        ;;
      "LXDE") TPecho "Installing the LXDE desktop Environment"
          pacstrap /mnt lxde 2>> feliz.log
          if [ -d /mnt/etc/lxdm ]; then
            echo "session=/usr/bin/startlxde" >> /mnt/etc/lxdm/lxdm.conf 2>> feliz.log
          fi
        ;;
      "LXQt") TPecho "Installing the LXQt desktop Environment"
        pacstrap /mnt lxqt oxygen-icons connman lxappearance xscreensaver 2>> feliz.log
        ;;
      "Mate") TPecho "Installing the Mate desktop Environment"
        pacstrap /mnt mate 2>> feliz.log
        TPecho "Installing the Mate extras package"
        pacstrap /mnt mate-extra 2>> feliz.log
        ;;
      "Openbox") TPecho "Installing the Openbox window manager"
        pacstrap /mnt openbox 2>> feliz.log
        ;;
      "Xfce") TPecho "Installing the Xfce desktop Environment"
        pacstrap /mnt xfce4 2>> feliz.log
        TPecho "Installing the Xfce goodies package"
        pacstrap /mnt xfce4-goodies 2>> feliz.log
        ;;
      *) continue # Ignore all others on this pass
      esac
    done
    
    # Install Yaourt
    TPecho "Modifying pacman.conf and installing Yaourt"
    cp pacman.conf /mnt/etc 2>> feliz.log # For installed system
    cp pacman.conf /etc 2>> feliz.log     # For installer
    pacman-key --init 2>> feliz.log
    pacman-key --populate archlinux 2>> feliz.log
    pacman -Sy 2>> feliz.log              # Update
    pacstrap /mnt yaourt 2>> feliz.log    # Then install Yaourt
    
    # Second parse through LuxuriesList - any extras
    for i in ${LuxuriesList}
    do
      case $i in
      "Budgie" | "Cinnamon" | "Deepin" | "Enlightenment" | "Fluxbox" | "Gnome" | "KDE" | "LXDE" | "LXQt" | "Mate" | "Openbox" | "Xfce") continue # Ignore DEs & WMs on this pass
        ;;
      "cairo-dock") TPecho "Installing cairo-dock & cairo-dock-plug-ins"
        pacstrap /mnt cairo-dock cairo-dock-plug-ins 2>> feliz.log
        ;;
      "conky") TPecho "Installing Conky"
        pacstrap /mnt conky 2>> feliz.log
        ;;
      *) TPecho "Installing $i"
        pacstrap /mnt $i 2>> feliz.log
      esac
    done
  fi

}

UserAdd() {
  CheckUsers=`cat /mnt/etc/passwd | grep ${UserName}`
  # If not already exist, create user
  if [ -z ${CheckUsers} ]; then
    TPecho "Adding user '${UserName}' and setting up groups"
    arch_chroot "useradd ${UserName} -m -g users -G wheel,storage,power,network,video,audio,lp -s /bin/bash"
    # Set up basic configuration files and permissions for user
    arch_chroot "cp /etc/skel/.bashrc /home/${UserName}"
    arch_chroot "chown -R ${UserName}:users /home/${UserName}"
    sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /mnt/etc/sudoers 2>> feliz.log
  else
    TPecho "User already exists"
  fi
}

SetRootPassword() {
  print_heading
  echo
  PrintOne "Success!"
  echo
  PrintOne "Finished installing in $DIFFMIN minutes and $DIFFSEC seconds"
  echo
  PrintOne "-----------------------"
  echo
  PrintOne "Finally we need to set passwords ..."
  echo
  PrintOne "Note that you will not be able to "
  PrintOne "see passwords as you enter them ..."
  echo
  Repeat="Y"
  while [ $Repeat = "Y" ]
  do
    read -s -p "Enter a password for root: " Pass1
    echo
    read -s -p "Re-enter password for root: " Pass2
    echo
    if [ -z ${Pass1} ] || [ -z ${Pass2} ]; then
      print_heading
      read_timed "Passwords cannot be blank. Try again ..." 1
      continue
    fi
    if [ $Pass1 = $Pass2 ]; then
     echo -e "${Pass1}\n${Pass2}" > /tmp/.passwd
     arch_chroot "passwd root" < /tmp/.passwd >/dev/null
     rm /tmp/.passwd 2>> feliz.log
     Repeat="N"
    else
      print_heading
      PrintOne "Passwords don't match. Try again"
    fi
  done
}

SetUserPassword() {
  echo
  Repeat="Y"
  while [ $Repeat = "Y" ]
  do
    read -s -p "Enter a password for $UserName: " Pass1
    echo
    read -s -p "Re-enter password for $UserName: " Pass2
    echo
    if [ -z ${Pass1} ] || [ -z ${Pass2} ]; then
      print_heading
      read_timed "Passwords cannot be blank. Try again ..." 1
      continue
    fi
    if [ $Pass1 = $Pass2 ]; then
      echo -e "${Pass1}\n${Pass2}" > /tmp/.passwd
      arch_chroot "passwd ${UserName}" < /tmp/.passwd >/dev/null
      rm /tmp/.passwd 2>> feliz.log
      Repeat="N"
    else
      print_heading
      echo "Passwords don't match. Try again"
      continue
    fi
  done
}
