#!/bin/bash

# The Feliz2 installation scripts for Arch Linux
# Developed by Elizabeth Mills
# Revision date: 11th January 2017

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation - either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
#      WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#            General Public License for more details.

# A copy of the GNU General Public License is available from the Feliz2
#        page at http://sourceforge.net/projects/feliz2/files
#        or https://github.com/angeltoast/feliz2, or write to:
#                 The Free Software Foundation, Inc.
#                  51 Franklin Street, Fifth Floor
#                    Boston, MA 02110-1301 USA
# In this module: functions for setting variables used during installation
# --------------------   ------------------------
# Function        Line   Function            Line
# --------------------   ------------------------
# not_found         41    SetHostname         491
# Echo              46    PickLuxuries        508
# TPread            51    KeepOrDelete        540
# SetKernel         67    ShoppingList        568
# ConfirmVbox       80    ChooseDM            670
# SetTimeZone      105    SetGrubDevice       728
# SetSubZone       137     --- Review stage ---
# America          173    FinalCheck          752
# setlocale        211    ManualSettings      859
# AllLanguages     363    ChangeRootPartition 882
# getkeymap        380    ChangeSwapPartition 890
# SearchKeyboards  441    ChangePartitions    898
# Username         475    AddExtras           910
# --------------------    -----------------------

not_found() {
  Echo
  read_timed "Not found. Please try again ..." 1
}

Echo() { # Use in place of 'echo' for basic text print
  printf "%-s\n" "$1"
  cursor_row=$((cursor_row+1))
}

TPread() { # Aligned prompt for user-entry
  # $1 = prompt ... Returns result through $Response
  local T_COLS=$(tput cols)
  local lov=${#1}
  local stpt=0
  if [ ${lov} -lt ${T_COLS} ]; then
    stpt=$(( (T_COLS - lov) / 2 ))
  elif [ ${lov} -gt ${T_COLS} ]; then
    stpt=0
  else
    stpt=$(( (T_COLS - 10) / 2 ))
  fi
  EMPTY="$(printf '%*s' $stpt)"
  read -p "$EMPTY $1" Response
  cursor_row=$((cursor_row+1))
}

SetKernel() {
  print_heading
  Echo
  PrintOne "Choose your kernel"
  PrintOne "The Long-Term-Support kernel (LTS) offers stabilty"
  PrintOne "while the Latest kernel has all the new features"
  PrintOne "If in doubt, choose LTS"
  Echo
  listgen1 "LTS Latest" "" "$_Ok"
  Kernel=${Response} # Set the Kernel variable (1 = LTS; 2 = Latest)
}

ConfirmVbox() {
  while :
  do
    print_heading
    PrintOne "It appears that feliz is running in Virtualbox"
    PrintOne "If it is, feliz can install Virtualbox guest"
    PrintOne "utilities and make appropriate settings for you"
    Echo
    PrintOne "Install Virtualbox guest utilities?"
    Echo
    Buttons "Yes/No" "$_Yes $_No" ""
    Echo
    case $Response in
      1) IsInVbox="VirtualBox"
      ;;
      "") invalid_option
        continue
      ;;
      *) IsInVbox=""
    esac
    return 0
  done
}

SetTimeZone() {
  SUBZONE=""
  until [ $SUBZONE ]
  do
    print_heading
    PrintOne "To set the system clock, please first"
    PrintOne "choose the World Zone of your location"
    Zones=$(timedatectl list-timezones | cut -d'/' -f1 | uniq) # Ten world zones
    Echo
    zones=""
    for x in ${Zones}                      # Convert to space-separated list
    do
      Translate "$x"                          # Translate
      zones="$zones $Result"
    done
    listgen1 "${zones}" "" "$_Ok"         # Allow user to select one
    # Because the list is translated, we need to get the system version of the selected item
    ZONE=$(echo "$Zones" | head -n $Response | tail -n 1)
    Echo
    case $Result in
      "") continue
      ;;
      *) SetSubZone                           # Call subzone function
        case $Result in                       # If user quits
        "Exit" | "") SUBZONE=
        ;;
        *) SUBZONE="$Result"
        esac
    esac
  done

}

SetSubZone() {  # Use ZONE set in SetTimeZone to list available subzones
  Translate "Please choose your nearest location"
  local _P1="$Result"
  case $ZONE in
  "Arctic") Result="Longyearbyen"
  ;;
  "Antarctica" | "Australia") print_heading
    PrintOne "$_P1" ""
    listgen1 "$(timedatectl list-timezones | grep ${ZONE}/ | cut -d'/' -f2)" "" "$_Ok $_Exit"
    if [ $Result = "Exit" ] || [ $Result = "" ]; then
      SetTimeZone
    fi
  ;;
  "Atlantic" | "Indian") print_heading
    PrintOne "$_P1" ""
    listgen1 "$(timedatectl list-timezones | grep ${ZONE}/ | cut -d'/' -f2)" "" "$_Ok $_Exit"
    if [ $Result = "Exit" ] || [ $Result = "" ]; then
      SetTimeZone
    fi
  ;;
  "Pacific") timedatectl list-timezones | grep ${ZONE}/ | cut -d'/' -f2 > temp.file
    listgenx "$_P1" "$_xNumber" "$_xExit" "$_xLeft" "$_xRight"
    if [ $Result = "Exit" ] || [ $Result = "" ]; then
      SetTimeZone
    fi
  ;;
  "America") America
   ;;
  *) timedatectl list-timezones | grep ${ZONE}/ | cut -d'/' -f2 > temp.file  # List of subzones
    listgenx "$_P1" "$_xNumber" "$_xExit" "$_xLeft" "$_xRight"
    if [ $Result = "Exit" ] || [ $Result = "" ]; then
      SetTimeZone
    fi
  esac
}

America() {
  SUBZONE=""      # Make sure this variable is empty
  print_heading
  PrintOne "Are you in any of these states?"
  SubList=""      # Start an empty list
  Previous=""     # Prepare to save previous record
  local Toggle="First"
  for i in $(timedatectl list-timezones | grep "$ZONE/" | cut -d'/' -f2)
  do
    if [ $Previous ] && [ $i = $Previous ] && [ $Toggle = "First" ]; then # First reccurance
      SubList="$SubList $i"
      Toggle="Second"
    elif [ $Previous ] && [ $i != $Previous ] && [ $Toggle = "Second" ]; then # 1st occ after prev group
      Toggle="First"
      Previous=$i
    else                                                                  # Subsequent occurances
      Previous=$i
    fi
  done
  SubGroup=""
  Translate "None_of_these"
  _None_of_these="$Result"
  SubList="$SubList $_None_of_these"        # Add a decline option
  listgen1 "$SubList" "" "$_Ok $_Exit"
    case $Result in
  "$_None_of_these") timedatectl list-timezones | grep $ZONE | grep -v 'Argentina\|Indiana\|Kentucky\|North_Dakota' | cut -d'/' -f2 > temp.file
     listgenx "$_P1" "$_xNumber" "$_xExit" "$_xLeft" "$_xRight"
  ;;
  '' | "Exit") SetTimeZone
  ;;
  *) SubGroup=$Result                     # Because America has some cities in subgroups
    print_heading
    PrintOne "Please choose your nearest location" "or Exit to go back"
    listgen1 "$(timedatectl list-timezones | grep ${ZONE}/${SubGroup} | cut -d'/' -f3)" "" "$_Ok $_Exit"
    if [ $Result = "" ] || [ $Result = "Exit" ]; then
      SetTimeZone
    fi
  esac
}

setlocale() { # Uses country-code in cities.list to match ZONE/SUBZONE to country-code,
                        # ... and hence to the list of languages generated from /etc/locale.gen
  ZoneID="${ZONE}/${SUBZONE}"         # Use a copy of zones set in SetTimeZone (eg: Europe/London)
  CountryLocale=
  while [ -z $CountryLocale ]
  do
  #  location=$(grep "$ZoneID" cities.list)      # Find location in cities.list
  #  SEARCHTERM=$(echo "${location}" | awk -F':' '{ print $2 }' ) # field $2 is the country code (eg: GB)
    SEARCHTERM=$(grep "$ZoneID" cities.list | cut -d':' -f2)  # Find in cities.list (field $2 is the country code, eg: GB)
    SEARCHTERM=${SEARCHTERM:0:2}                # Ensure no trailing spaces
    print_heading
    # Find all matching entries in locale.gen # This will be a table of locales in the form: en_GB
  #  LocaleList=$(grep ${SEARCHTERM}.UTF-8 /etc/locale.gen | grep -v "@" | cut -d' ' -f2 | cut -d'.' -f1 | sort | uniq)
    LocaleList=$(grep "#" /etc/locale.gen | grep ${SEARCHTERM}.UTF-8 | cut -d'.' -f1 | cut -d'#' -f2)
    HowMany=$(echo $LocaleList | wc -w)   # Count them
    Rows=$(tput lines)       # to ensure menu doesn't over-run
    Rows=$((Rows-4))         # Available (printable) rows
    case $HowMany in         # Offer language options for the selected country
    0) print_heading
      Echo
      PrintOne "No language has been found for your location"
      PrintOne "Would you like to use one of the following?"
      listgen1 "English French Spanish" "$_Instructions" "$_Ok $_Exit"
      case $Response in
      1) Item="en"
      ;;
      2) Item="fr"
      ;;
      3) Item="es"
      ;;
      *) City=""
        AllLanguages
        if [ $Result = "Exit" ]; then
          SetTimeZone
        else
          Item=$(grep "${Language}:" languages.list)
          Item=${Item: -2:2}
          CountryLocale="${Item}_${SEARCHTERM}.UTF-8"
          CountryCode=${CountryLocale:3:2}        # 2 characters from position 3
        fi
      esac
      CountryLocale="${Item}_${SEARCHTERM}.UTF-8"
      CountryCode=${CountryLocale:3:2}            # 2 characters from position 3
    ;;
    1) Item="${LocaleList:0:2}"     # First two characters of the record in locale.gen (eg: en)
      Language="$(grep :$Item languages.list | cut -d':' -f1)"
      if [ -z $Language ] || [ $Language = "" ]; then  # If language name not found in languages.list
        Language=$Item                                 # Use the abbreviation
      fi
      Echo
      Translate "Only one language found for your location"
      PrintOne "$Result" ": $Language"
      PrintOne "Shall we use this as your language?"  # Allow user to confirm
      Buttons "Yes/No" "$_Yes $_No" ""
      if [ $Result = "$N" ]; then
        City=""
        AllLanguages
        if [ $Result = "Exit" ] || [ $Result = "exit" ]; then
          SetTimeZone
        else
          Item=$(grep "${Language}:" languages.list)
          Item=${Item: -2:2}
          CountryLocale="${Item}_${SEARCHTERM}.UTF-8"
          CountryCode=${CountryLocale:3:2}              # 2 characters from position 3
        fi
      else
        Item=$(grep "${Language}:" languages.list)
        Item=${Item: -2:2}
        CountryLocale="${Item}_${SEARCHTERM}.UTF-8"
        CountryCode=${CountryLocale:3:2}              # 2 characters from position 3
      fi
    ;;
    *) # Check the short code for each language against long names in language.list
      if [ $HowMany -ge $Rows ]; then                 # Too many to display in menu, so use listgenx
        # Make a shortlist of relevant language codes
        ShortList=$(grep ${SEARCHTERM}.UTF-8 /etc/locale.gen | cut -d' ' -f2 | cut -c 1-2 | uniq)
        for l in ${ShortList}
        do
          grep "$l$" languages.list >> temp.file
        done
        Translate "Now please choose your language from this list"
        listgenx "$Result" "$_xNumber" "$_xExit" "$_xLeft" "$_xRight"
      else
        local Counter=0
        localelist=""
        for l in ${LocaleList[@]}                       # Convert to space-separated list
        do
          localelist="${localelist} $l"                 # Add each item to text list for handling
          Counter=$((Counter+1))
        done
        if [ $Counter -eq 0 ]; then                     # If none found, try again
          not_found
          SetTimeZone
        fi
        Counted=$(echo $localelist | wc -w)             # Count number of words in $localelist
        Newlist=""                                      # Prepare to make list of language names from codes
        for (( i=1; i <= Counted; ++i ))
        do                                              # For each item in localelist (eg: en_GB)
          loc=$(echo $localelist | cut -d' ' -f$i)      # Save the $i-th item from localelist
          Newlist="$Newlist ${loc:0:2}"                 # Add first two characters (language code) to list
        done
        # If more than one language found
        localelist="${Newlist}"                         # Save the list to continue
        Newlist=""                                      # Prepare new empty list
        Prev="xyz"                                      # Arbitrary comparison
        for l in $localelist                            # Remove any duplicates
        do
          if [ $l != $Prev ]; then
            Newlist="$Newlist $l"
            Prev=$l
          fi
        done
        localelist="${Newlist}"                         # Copy to working variable
        choosefrom=""
        Newlist=""                                      # Empty new list again
        Counter=0                                       # Prepare to limit length of file
        for l in ${localelist}
        do                                              # Find the language in languages.list
          Item="$(grep $l\$ languages.list | cut -d':' -f1)"
          if [ $Item ]; then                            # If found
            choosefrom="$choosefrom $Item"              # Add to list of languages for user
            Newlist="$Newlist $l"                       # ... and a matching list of codes
          fi
          Counter=$((Counter+1))
        done
        localelist="${Newlist}"                         # Ensure that localelist matches choosefrom
        print_heading
        PrintOne "Now please choose your language from this list" "" "or Exit to try again."
        listgen1 "${choosefrom}" "" "$_Ok $_Exit"         # Menu if less than one screenful
      fi
      case $Result in
      "Exit" | "exit" | "") SetTimeZone
      ;;
      *) Language=$(grep $Result languages.list)        # Lookup the result in languages file
        if [ $Language ]; then
          loc=${Language: -2:2}                         # Just the last two characters
          CountryLocale="${loc}_${SEARCHTERM}.UTF-8"
          CountryCode=${CountryLocale:3:2}              # 2 characters from position 3
        else
          SetTimeZone
        fi
      esac
    esac
  done
}

AllLanguages() {
  while :
  do
    print_heading
    Echo
    cat languages.list > temp.file         # Prepare file for listgenx to display all languages
    Translate "Now please choose your language from this list"
    listgenx "$Result" "$_xNumber" "$_xExit" "$_xLeft" "$_xRight"
    if [ $Result = "" ] || [ $Result = "Exit" ]; then
      SetTimeZone                                   # Start again from time zone
    else
      Result="${Result: -2:2}"                      # Pass short code back to caller
      break
    fi
  done
}

getkeymap() {
  Countrykbd=""
  country="${CountryLocale,,}"
  case ${country:3:2} in
  "gb") Term="uk"
  ;;
  *) Term="${country:3:2}"
  esac
  ListKbs=$(cat keymaps.list | grep ${Term})
  Found=$(cat keymaps.list | grep ${Term} | wc -l)  # Count records
  if [ ! $Found ]; then
    Found=0
  fi
  while [ -z "$Countrykbd" ]
  do
    print_heading
    Echo
    case $Found in
    0)  # If the search found no matches
      Translate "Sorry, no keyboards found based on your location"
      read_timed "$Result" 2
      SearchKeyboards
    ;;
    1)  # If the search found one match
      PrintOne "Only one keyboard found based on your location"
      PrintOne "Do you wish to accept this? Select No to search for alternatives"
      Buttons "Yes/No" "$_Yes $_No" "$_Instructions"
      case ${Result} in
      "Exit"|"exit"|""|"$N") SearchKeyboards
      ;;
      *) Countrykbd="${Result}"
      esac
      loadkeys ${Countrykbd} 2>> feliz.log
    ;;
    *) # If the search found multiple matches, check to ensure menu doesn't over-run
      Rows=$(tput lines)
      Rows=$((Rows-7))    # Available (printable) rows
      if [ $Found -ge $Rows ]; then
        for i in $ListKbs
        do
          echo $i >> temp.file
        done
        Translate "Choose one, or ' ' to search for alternatives"
        listgenx "$Result" "$_xNumber" "$_xExit" "$_xLeft" "$_xRight"
      else
        PrintOne "Choose one or Exit to search for alternatives"
        listgen1 "$ListKbs" "" "$_Ok $_Exit"
      fi
      case ${Result} in
      "Exit"|"exit"|"") SearchKeyboards
      ;;
      *) Countrykbd="${Result}"
      esac
      loadkeys ${Countrykbd} 2>> feliz.log
    esac
  done
}

SearchKeyboards() {
  while [ -z "$Countrykbd" ]
  do
    print_heading
    PrintOne "If you know the code for your keyboard layout, please enter"
    PrintOne "it now. If not, try entering a two-letter abbreviation"
    PrintOne "for your country or language and a list will be displayed"
    PrintOne "Alternatively, enter 'Exit' to start again"
    Echo
    TPread "(eg: 'dvorak' or 'us'): "
    local Term="${Response,,}"
    if [ $Term = "exit" ]; then
      SetTimeZone
    fi
    Echo
    ListKbs=$(cat keymaps.list | grep ${Term})
    if [ -n "${ListKbs}" ]; then  # If a match or matches found
      print_heading
      PrintOne "Select your keyboard, or Exit to try again"
      listgen1 "$ListKbs" "" "$_Ok $_Exit"
      if [ "${Result}" = "Exit" ]; then
        continue
      else
        Countrykbd="${Result}"
      fi
      loadkeys ${Countrykbd} 2>> feliz.log
    else
      print_heading
      Echo
      PrintOne "No keyboards found containing" "'$Term'"
      PrintOne "Please try again"
    fi
  done
}

UserName() {
  print_heading
  PrintOne "Enter a name for the primary user of the new system"
  PrintOne "If you don't create a username here, a default user"
  PrintOne "called 'archie' will be set up"
  Echo
  Translate "User Name"
  TPread "$Result: "
  Entered=${Response,,}
  case $Entered in
    "") UserName="archie"
    ;;
    *) UserName=${Entered}
  esac
}

SetHostname() {
  Entered="arch-linux"
  print_heading
  PrintOne "A hostname is needed. This will be a unique name to identify"
  PrintOne "your device on a network. If you do not enter one, the"
  PrintOne "default hostname of 'arch-linux' will be used"
  Echo
  Translate "Enter a hostname for your computer"
  TPread "${Result}: "
  Entered=${Response,,}
  case $Entered in
    "") HostName="arch-linux"
    ;;
    *) HostName=${Entered}
  esac
}

PickLuxuries() { # User selects any combination from a store of extras
  CategoriesList=""
  Translate "Added so far"
  AddedSoFar="$Result"
  for category in Accessories Desktop_Environments Graphical Internet Multimedia Office Programming Window_Managers
  do
    Translate "$category"
    CategoriesList="$CategoriesList $Result"
  done
  print_heading
  case "$LuxuriesList" in
  '') PrintOne "Now you have the option to add extras, such as a web browser"
    PrintOne "desktop environment, etc, from the following categories"
    PrintOne "If you want only a base Arch installation"
    PrintOne "exit without choosing any extras"
  ;;
  *) PrintOne "You can add more items, or select items to delete"
  esac
  Echo
  while :
  do
    listgen1 "${CategoriesList}" "" "$_Ok $_Exit"
    Category=$Response
    if [ $Result = "Exit" ]; then
      break
    else
      ShoppingList
      print_heading
      PrintOne "$AddedSoFar" ": ${LuxuriesList}"
      PrintOne "You can now choose from any of the other lists"
      PrintOne "or choose Exit to finish this part of the setup"
    fi
  done
  if [ -n "${LuxuriesList}" ]; then
    Scope="Full"
  else
    Scope="Basic"
  fi
}

KeepOrDelete() {
  Bagged="$1"
  while :
  do
    print_heading
    Translate "is already in your shopping list"
    Message="$Bagged $Result"
    Translate "Keep"
    K="$Result"
    Translate "Delete"
    D="$Result"
    Buttons "Yes/No" "$K $D" "$_Instructions"
    case $Response in
      1) Temp="$LuxuriesList"
        break
      ;;
      2) Validated="Y"
        Temp=""
        for lux in $LuxuriesList
        do
          if [ ${lux} != ${Bagged} ]; then
            Temp="$Temp $lux"
          fi
        done
        break
      ;;
      *) invalid_option
    esac
  done
  LuxuriesList="$Temp"
}

ShoppingList() { # Called by PickLuxuries after a category has been chosen.
  Translate "Choose an item"
  Passed="$Result"
  while :
  do
    print_heading
    PrintOne "$AddedSoFar" ": ${LuxuriesList}"
    Echo
    PrintOne "${Categories[$Category]}" # $Category is number of item in CategoriesList
    # Pass category to listgen2 for user to choose one item;
    local Counter=1
    case $Category in
       1) OptionsCounter=1
          for Option in "${LongAccs[@]}"  # Translate all elements
          do
            Translate "$Option"
            LongAccs[${OptionsCounter}]="$Result"
            (( OptionsCounter+=1 ))
          done
        for i in ${Accessories}
        do
          LongAccs1[${Counter}]="$i - ${LongAccs[${Counter}]}"
          (( Counter+=1 ))
        done
        listgen2 "$Accessories" "" "$_Ok $_Exit" "LongAccs1"
       ;;
       2) OptionsCounter=1
          for Option in "${LongDesk[@]}"  # Translate all elements
          do
            Translate "$Option"
            LongDesk[${OptionsCounter}]="$Result"
            (( OptionsCounter+=1 ))
          done
        for i in ${Desktops}
        do
          LongDesk1[${Counter}]="$i - ${LongDesk[${Counter}]}"
          (( Counter+=1 ))
        done
        listgen2 "$Desktops" "" "$_Ok $_Exit" "LongDesk1"
       ;;
       3) OptionsCounter=1
          for Option in "${LongGraph[@]}"  # Translate all elements
          do
            Translate "$Option"
            LongGraph[${OptionsCounter}]="$Result"
            (( OptionsCounter+=1 ))
          done
        for i in ${Graphical}
        do
          LongGraph1[${Counter}]="$i - ${LongGraph[${Counter}]}"
          (( Counter+=1 ))
        done
        listgen2 "$Graphical" "" "$_Ok $_Exit" "LongGraph1"
       ;;
       4) OptionsCounter=1
          for Option in "${LongNet[@]}"  # Translate all elements
          do
            Translate "$Option"
            LongNet[${OptionsCounter}]="$Result"
            (( OptionsCounter+=1 ))
          done
        for i in ${Internet}
        do
          LongNet1[${Counter}]="$i - ${LongNet[${Counter}]}"
          (( Counter+=1 ))
        done
        listgen2 "$Internet" "${Headline}" "$_Ok $_Exit" "LongNet1"
       ;;
       5) OptionsCounter=1
          for Option in "${LongMulti[@]}"  # Translate all elements
          do
            Translate "$Option"
            LongMulti[${OptionsCounter}]="$Result"
            (( OptionsCounter+=1 ))
          done
        for i in ${Multimedia}
        do
          LongMulti1[${Counter}]="$i - ${LongMulti[${Counter}]}"
          (( Counter+=1 ))
        done
        listgen2 "$Multimedia" "" "$_Ok $_Exit" "LongMulti1"
       ;;
       6) OptionsCounter=1
          for Option in "${LongOffice[@]}"  # Translate all elements
          do
            Translate "$Option"
            LongOffice[${OptionsCounter}]="$Result"
            (( OptionsCounter+=1 ))
          done
        for i in ${Office}
        do
          LongOffice1[${Counter}]="$i - ${LongOffice[${Counter}]}"
          (( Counter+=1 ))
        done
        listgen2 "$Office" "" "$_Ok $_Exit" "LongOffice1"
       ;;
       7) OptionsCounter=1
          for Option in "${LongProg[@]}"  # Translate all elements
          do
            Translate "$Option"
            LongProg[${OptionsCounter}]="$Result"
            (( OptionsCounter+=1 ))
          done
        for i in ${Programming}
        do
          LongProg1[${Counter}]="$i - ${LongProg[${Counter}]}"
          (( Counter+=1 ))
        done
        listgen2 "$Programming" "" "$_Ok $_Exit" "LongProg1"
       ;;
       8) OptionsCounter=1
          for Option in "${LongWMs[@]}"  # Translate all elements
          do
            Translate "$Option"
            LongWMs[${OptionsCounter}]="$Result"
            (( OptionsCounter+=1 ))
          done
        for i in ${WindowManagers}
        do
          LongWMs1[${Counter}]="$i - ${LongWMs[${Counter}]}"
          (( Counter+=1 ))
        done
        listgen2 "$WindowManagers" "" "$_Ok $_Exit" "LongWMs1"
      ;;
      *) break
    esac
    Passed="$Result" # Loop until user selects "Exit"
    if [ $Passed = "Exit" ]; then
      break
    fi

    AddToList="Y"
    # First check that chosen item is not already on the list
    for lux in $LuxuriesList
    do
      if [ ${lux} = ${Result} ]; then
        KeepOrDelete "$Result" # New function
        Result=""
        continue
      fi
    done
    # Then carry out any specific tests and add the item to the list
    SaveResult=$Result # (Because other subroutines return $Result)
    case $SaveResult in
      "Budgie" | "Cinnamon" | "Deepin" | "Enlightenment" | "Fluxbox" | "Gnome" | "KDE" | "LXDE" | "LXQt" |  "Mate" | "Openbox" | "Xfce") DesktopEnvironment=$SaveResult

       ;;
      "") continue
       ;;
      *) Echo
    esac
    if [ ${SaveResult} = "libreoffice" ]; then
      LuxuriesList="${LuxuriesList} libreoffice-fresh"
    else
      LuxuriesList="${LuxuriesList} ${SaveResult}"
    fi
  done
  Passed=""     # Clear the information variable
}

ChooseDM() { # Choose a display manager
  case $DisplayManager in
  "") # Only offered if no other display manager has been set
      Counter=0
      Greeter=""
      DMList="GDM LightDM LXDM sddm SLIM XDM"
      print_heading
      PrintOne "A display manager provides a graphical login screen"
      PrintOne "If in doubt, choose LightDM"
      PrintOne "If you do not install a display manager, you will have"
      PrintOne "to launch your desktop environment manually"
      Echo
      listgen1 "${DMList}" "" "$_Ok $_Exit"
      Reply=$Response
      for item in ${DMList}
      do
        Counter=$((Counter+1))
        if [ $Counter -eq $Reply ]
        then
          SelectedDM=$item
          case $SelectedDM in
            "GDM") DisplayManager="gdm"
              ;;
            "LightDM") DisplayManager="lightdm"
                  Greeter="lightdm-gtk-greeter"
              ;;
            "LXDM") DisplayManager="lxdm"
              ;;
            "sddm") DisplayManager="sddm"
              ;;
            "SLIM") DisplayManager="slim"
              ;;
            "XDM") DisplayManager="xdm"
              ;;
            *) DisplayManager=""
          esac
          break
        fi
      done
    ;;
  *) # Warn that DM already set, and offer option to change it
      print_heading
      PrintOne "Display manager is already set as" ":" "" "$DisplayManager."
      PrintOne "Only one display manager can be active"
      Echo
      PrintOne "Do you wish to change it?"
      Echo
      Buttons "Yes/No" "$_Yes $_No" "$_Instructions"
      Echo
      if [ $Response -eq 1 ]; then    # User wishes to change DM
        DisplayManager=""             # Clear DM variable
        Greeter=""                    # and greeter
        ChooseDM                      # Call this function again
      fi
  esac
}

SetGrubDevice() {
  DEVICE=""
  DevicesList="$(lsblk -d | awk '{print "/dev/" $1}' | grep 'sd\|hd\|vd')"  # Preceed field 1 with '/dev/' # This is good use of awk
  print_heading
  GrubDevice=""
  local Counter=0
  PrintOne "Select the device where Grub is to be installed"
  PrintOne "Note that if you do not select a device, Grub"
  PrintOne "will not be installed, and you will have to make"
  PrintOne "alternative arrangements for booting your new system"
  Echo
  listgen1 "${DevicesList}" "" "$_Ok $_Exit"
  Reply=$Response
  for i in ${DevicesList}
  do
    Item=$i
    Counter=$((Counter+1))
    if [ $Counter -eq $Reply ]; then
      GrubDevice=$Item
      break
    fi
  done
}

FinalCheck() {
  while :
  do
    print_heading
    PrintOne "These are the settings you have entered. Please check them"
    Echo
    if [ ${UEFI} -eq 1 ]; then
      PrintOne "0)  $_BootPartition " "... $EFIPartition                       "
      Translate "/root partition"
      PrintMany "1)  $_RootPartition " "... $RootPartition : $RootType"
    else
      PrintOne "1)  $_RootPartition" "... $RootPartition : $RootType           "
    fi
    if [ $SwapPartition ] || [ $SwapFile ]; then
      PrintMany "2)  $_SwapPartition" "... $SwapPartition $SwapFile"
    else
      Translate "No provision has been made for swap"
      PrintMany "2) " "$Result"
    fi
    if [ ${#AddPartList[@]} -gt 0 ]; then
      Counter=0
      Translate "Extra partitions"
      PrintMany "3)  $Result" "..."
      for i in ${AddPartList[@]}
      do
        PrintMany "     ${AddPartMount[$Counter]} " ": ${AddPartList[$Counter]} : ${AddPartType[$Counter]}"
        Counter=$((Counter+1))
      done
    else
      Translate "No additional partitions have been allocated"
      PrintMany "3) " "$Result"
    fi
    case $Kernel in
      1) Translate "The LTS kernel will be installed"
        PrintMany "4) " "$Result"
      ;;
      *) Translate "The latest kernel will be installed"
        PrintMany "4) " "$Result"
    esac
    if [ $GrubDevice ]; then
      Translate "Grub will be installed to"
      PrintMany "5)  $Result" "$GrubDevice"
    else
      Translate "No provision has been made for Grub"
      PrintMany "5) " "$Result"
    fi
      Translate "Zone/subZone will be"
      PrintMany "6)  $Result" "$ZONE/$SUBZONE"
      Translate "Locale will be set to"
      PrintMany "7)  $Result" "$CountryLocale"
      Translate "Keyboard is"
      PrintMany "8)  $Result" "$Countrykbd"
    case ${IsInVbox} in
      "VirtualBox") Translate "Virtualbox guest utilities will be installed"
      PrintMany "9) " "$Result"
      ;;
      *) Translate "Virtualbox guest utilities will not be installed"
      PrintMany "9) " "$Result"
    esac
    if [ -z $DisplayManager ]; then
      Translate "No Display Manager selected"
      PrintMany "10)" "$Result"
    else
      Translate "Display Manager"
      PrintMany "10) $Result" " = $DisplayManager"
    fi
    Translate "Root and user settings"
    PrintMany "11) $Result" "..."
    Translate "Hostname"
    PrintMany "      $Result" "= '$HostName'"
    Translate "User"
    PrintMany "      $Result" "= '$UserName'"
    Translate "The following extras have been selected"
    PrintMany "12) $Result" "..."
    PrintOne "${LuxuriesList}" ""
    Echo
    PrintOne "Press Enter to install with these settings, or"
    Response=20
    Translate "Enter number for data to change"
    TPread "${Result}: "
    Change=$Response
    case $Change in
      1) ChangeRootPartition
        AllocateRoot
        continue
      ;;
      2) ChangeSwapPartition
        AllocateSwap
        continue
      ;;
      3) ChangePartitions
        MorePartitions
        continue
      ;;
      4) SetKernel
        continue
      ;;
      5) SetGrubDevice
        continue
      ;;
      6) SetTimeZone
        continue
      ;;
      7) setlocale
        continue
      ;;
      8) getkeymap
        continue
      ;;
      9) ConfirmVbox
        continue
      ;;
      10) DisplayManager=""
        ChooseDM
        continue
      ;;
      11) ManualSettings
        continue
      ;;
      12) PickLuxuries
        continue
      ;;
      *) break
    esac
  done
}

ManualSettings() {
  while :
  do
    print_heading
    PrintOne "Enter number for data to change"
    PrintOne "or ' ' to exit"
    Echo
    Translate "Hostname (currently"
    PrintOne "1) $Result" "${HostName})"
    Translate "Username (currently"
    PrintMany "2) $Result" "${UserName})"
    Echo
    Translate "Enter the number of your selection"
    TPread "${Result}: "
    Echo
    case $Response in
      1) Translate "Enter new Hostname (currently"
        TPread "${Result} ${HostName}): "
         HostName=$Response
        ;;
      2) Translate "Enter new username to be created (currently"
      TPread "${Result} ${UserName}) : "
         UserName=$Response
        ;;
      *) return 0
    esac
  done
}

ChangeRootPartition() {
# Start array with SwapPartition
  Ignorelist[0]=${SwapPartition}
  local Counter=1
  AddExtras
  MakePartitionList
}

ChangeSwapPartition() {
# Start array with RootPartition
  Ignorelist[0]=${RootPartition}
  Counter=1
  AddExtras
  MakePartitionList
}

ChangePartitions() {
  # Copy RootPartition and SwapPartition into temporary array
  Ignorelist[0]=${RootPartition}
  local Counter=1
  if [ ${SwapPartition} ]; then
    Ignorelist[1]=${SwapPartition}
    Counter=2
  fi
  Ignores=${#Ignorelist[@]} # Save a count for later
  MakePartitionList
}

AddExtras() {
  # Ignorelist started and Counter set to next record number by calling
  # function ChangeSwapPartition or ChangeRootPartition
  # Add each field (extra partition) from AddPartList into the array:
  for a in ${AddPartList[@]}; do
    Ignorelist[$Counter]=$a
    Counter=$((Counter+1))
  done
  Ignores=${#Ignorelist[@]} # Save a count for later
}
