#!/bin/bash

# menugen - menu functions used throughout Achoo

# Developed by Elizabeth Mills

PrintOne() { # Aligned text according to screen size
  width=`tput cols`
  lov=${#1}
  if [ ${lov} -lt ${width} ]; then
    stpt=$(( ($width - $lov) / 2 ))
    EMPTY="$(printf '%*s' $stpt)"
    echo "$EMPTY $1"
  else
    echo "$1"
  fi
}

PrintMany() { # Subsequent item(s) in an aligned list
  echo "$EMPTY $1"
}

menugen1() { # Simple listing alternative to the bash 'select' function
# Read Menuing.manual for full details
local Complete=0
while [ $Complete -eq 0 ]
do
  if [ -n "${Passed}" ]; then
    PrintOne "$Passed"
  fi
  local Done=$3
  if [ -n $2 ]; then
    PrintOne $2
    Underscore=`echo $2 | sed 's/./-/g'`
    PrintOne $Underscore
  fi
  local Counter=0
  MenuList=$1
  for i in $MenuList
  do
    Counter=$((Counter+1))
    if [ $Counter -eq 1 ]; then
      PrintOne "$Counter) $i"
    else
      PrintMany "$Counter) $i"
    fi
    ConvertToArray[$Counter]=$i
  done
  case $Done in
    "") Counter=$((Counter+1))
        Done="Done"
        PrintMany "$Counter) Done"
    ;;
    "nodone") Done=""
    ;;
    *) Counter=$((Counter+1))
        PrintMany "$Counter) ${Done}"
  esac
  echo
  TPread "Please enter the number of your selection: "
  case $Response in
    ''|*[!0-9]*) invalid_option
    ;;
    *) if [ ${Response} -gt ${Counter} ] || [ ${Response} -lt 1 ]; then
        invalid_option
      elif [ ${Response} -eq ${Counter} ] && [ -z $Done ]; then
        Result=${ConvertToArray[${Response}]}
        Complete=1
      elif [ ${Response} -eq ${Counter} ]; then
        Result="$Done"
        Complete=1
      else
        Result=${ConvertToArray[${Response}]}
        Complete=1
      fi
  esac
  clear
done
}

menugen2() { # Previously 'InfoMenu'
# Advanced menuing function with extended descriptions linked to short name
# Parameters:
# 1) Primary file (string of single-word references)
# 2) An optional one-word menu heading (which will be underlined on display)
# 4) Secondary file (the name of the array containing long descriptions)
# 3) Optional alternative word to 'Done'
# Global variable $Passed may be used as page heading 
# If $Passed is not empty, it is displayed at the top of the page
local Complete=0
while [ $Complete -eq 0 ]
do
  local Done=$3
  Result=""
  PrimaryFile="$1"
  name=$4[@]
  LongDescription=("${!name}")
  local Counter=0
  if [ -n "${Passed}" ]; then
    PrintOne "$Passed"
  fi
  echo
  if [ -n $2 ]; then
    PrintOne $2
    Underscore=`echo $2 | sed 's/./-/g'`
    PrintOne $Underscore
  fi
  Counter=0
  for i in "${LongDescription[@]}"; do
    Counter=$((Counter+1))
    if [ $Counter -eq 1 ]; then
      PrintOne "${Counter}) $i"
    else
      PrintMany "${Counter}) $i"
    fi
  done
  case $Done in
    "") Counter=$((Counter+1))
        Done="Done"
        PrintMany "$Counter) Done"
    ;;
    "nodone") Done=""
    ;;
    *) Counter=$((Counter+1))
        PrintMany "$Counter) ${Done}"
  esac
  echo
  TPread "Please enter the number of your selection: "
  
   case $Response in
    ''|*[!0-9]*) invalid_option
    ;;
    *) if [ ${Response} -gt ${Counter} ]; then
      invalid_option
      elif [ ${Response} -eq ${Counter} ]; then
        Result="$Done"
        Complete=1
      else
        local Match=0
        for i in $PrimaryFile; do
          Match=$((Match+1))
          if [ $Match -eq $Response ]; then
            Result="$i"
          fi
        done
        Complete=1
      fi
  esac 
  clear
done
}
