#!/bin/bash

# listgen - Dialog menu functions used throughout Feliz
# Adapted by Elizabeth Mills from the cli version to use Dialog

# Both functions return the selected item as text using global variable $Result
# and errorcode as $Response (to remain consistent with the cli version as far as possible)

# listgen1 receives three parameters:
# 1) Primary file (string of single-word references)
# 2) Optional one-word --title
# 3) Optional hiding of <Cancel>

# listgen2 has extended descriptions using the name of the complex array
# Passed as 4th parameter:

# Global variable $Passed may be used as --backtitle

listgen1() {
  local Backtitle="$Passed"
  local Title="$2"
  if [ -n $3 ]; then
    local Nocancel="--$3"
  fi
  local Counter=0
  # Prepare $1 for dialog menu
  for part in $1 # Prepare string array of list items passed as $1
  do
    Counter=$((Counter+1))
    Options[${Counter}]="$part"
    Counter=$((Counter+1))
    Options[${Counter}]="-"
  done
  Counter=$((Counter/2))
  Printit
}

listgen2() { 
  local Backtitle="$Passed"
  local Title="$2"
  if [ -n $3 ]; then
    local Nocancel="--$3"
  fi
  local Counter=0
  for item in $1; do
    Items[${Counter}]=$item
    Counter=$((Counter+1))
  done
  Counter=0
  local ItemCounter=0
  # Import the complex array
  name=$4[@]
  LongName=("${!name}")
  # Prepare $1 and $4 for dialog menu
  for part in "${LongName[@]}"; do
    Options[$((Counter))]="${Items[${ItemCounter}]}"
    Options[$((Counter+1))]="$part"
    Counter=$((Counter+2))
    ItemCounter=$((ItemCounter+1))
  done
  Printit # The final frontier
}

Printit() {
  # Use $Counter and ${Options[@]} array in dialog
  Counter=$((Counter/2))
  dialog --backtitle "$Backtitle" --title " $Title " \
      --menu "\n$Message\n" 18 40 $Counter "${Options[@]}" 2> output.file
      
  Response=$? # Errorcode
  Result=$(cat output.file) # Selected item
}
