#!/bin/bash
  
testbed() {
  
# 
( set -o posix ; set ) >/tmp/variables.before
CopyArray[1]="Swap"
CopyArray[2]="Root"
CopyArray[3]="-"
CopyArray[4]="Swap file"
PartitionList="sda1 sda2 sda3"
  listgen2 "$PartitionList" "Partitions" "" "CopyArray"
( set -o posix ; set ) >/tmp/variables.after
diff /tmp/variables.before /tmp/variables.after
rm /tmp/variables.before /tmp/variables.after
}

# ~~~~~~~
# Execute
# ~~~~~~~
  
# First check for external functions and variables files
  if [[ -f `pwd`/felizfuncs ]]; then
    source felizfuncs
  else
    echo "missing file: felizfuncs"
    exit 1
  fi
  
  if [[ -f `pwd`/felizparts ]]; then
    source felizparts
  else
    echo "missing file: felizparts"
    exit 1
  fi
  
  if [[ -f `pwd`/felizdesktop ]]; then
    source felizdesktop
  else
    echo "missing file: felizdesktop"
    exit 1
  fi
 
  if [[ -f `pwd`/listgen ]]; then
    source listgen
  else
    echo "missing file: listgen"
    exit 1
  fi
  
  # Various variables
  UEFI=0
#  RootPartition="sda10"
#  RootType="ext4"
#  SwapPartition="sda7"
#  PartitionList="sda2 sda3"
#  AddPartList[0]="sda9"
#  AddPartLabel[0]="/home"
#  AddPartType[0]="ext4"
#  AddPartList[1]="sda5"
#  AddPartLabel[1]="/spare"
#  AddPartType[1]="ext4"
#  GrubDevice="/dev/sda"
#  CountryCode="GB"
#  CountryLocale="en_GB.UTF-8"
#  Countrykbd="uk"
#  ZONE="Europe"
#  SUBZONE="London"
#  DesktopEnvironment="xfce4"
#  DisplayManager="lightdm"
#  Greeter="lightdm-gtk-greeter"
#  LuxuriesList="firefox libreoffice-still geany pamac-aur"
#  HostName="ArchLinux"
#  RootPassword="Root"
#  UserName="archie"
#  UserPassword="Linux"
#  DesktopEnvironment="Gnome"
# Colours
Red='\e[0;31m';
Gre='\e[0;32m';
Yel='\e[0;33m';
Blu='\e[0;34m';
Pur='\e[0;35m';
Cya='\e[0;36m';
BRed='\e[1;31m';
BGre='\e[1;32m';
BYel='\e[1;33m';
BBlu='\e[1;34m';
BPur='\e[1;35m';
BCya='\e[1;36m';
UYel='\e[4;33m';
NoCol='\e[0;00m';  

# Call the function 'testbed' holding code to be tested
testbed
echo $* # Add any variables needed for viewing before exit
echo "End of test"
  
exit
  
  # Code for checking arrays
  Counter=0
  for i in ${AddPartList[@]}	
  do
    echo ${AddPartList[$Counter]}
    echo ${AddPartLabel[$Counter]} 
    echo ${AddPartType[$Counter]}
    Counter=$((Counter+1))
  done
  
