#!/bin/bash

# feliz (formerly Achoo!) Arch Linux Installation Script
# cliff edition - Command Line Interface Functions

# Developed by Elizabeth Mills with acknowledgement to Carl Duff
# Version: 2016-04-07

#
# Include source files
#
source shared
source various
source partitioning
source desktop
source listgen

StartTime=$(date +%s)
echo "$StartTime" >> feliz.log
clear

# Check partition table & offer options
CheckParts

if [ $AutoPart -eq 0 ]; then
  BuildPartitionLists # Display information about the available partitions
  AllocateRoot
  if [ -n "${PartitionList}" ]
  then
    AllocateSwap  # Display remaining partitions and allocate swap
  fi
  if [ -n "${PartitionList}" ]  # Check contents of PartitionList again
  then
    MorePartitions
  fi
fi

# Select kernel and device for Grub
SetKernel
if [ $AutoPart -eq 0 ]; then
  SetGrubDevice
fi

# Keyboard layout
getkeymap

# Localisation
SetTimeZone
setlocale
SetHostname

# Add extras
PickLuxuries
if [ $Scope != "Basic" ]; then
  UserName
  IsInVbox=`dmidecode --type 1 | grep 'Product Name' | cut -c 16-`
  if [ ${IsInVbox} = "VirtualBox" ]; then
    ConfirmVbox
  else
    IsInVbox=""
  fi
fi

# Allow user to change any variables
FinalCheck

#
# No further user intervention from here -------------------------------
#

print_heading
read_timed "Entering the automatic phase of installation." 1
read_timed "No further user intervention is necessary." 1
read_timed "Go make yourself a cup of tea; you deserve it." 1

MountPartitions # cliff/various

# Set mirrorlist
ReflectorMirrorList # common/shared

# Install kernel
InstallKernel # cliff/various

# Set the default PATH variable
arch_chroot "PATH=/usr/lib/systemd/system:/etc/systemd/system:/usr/local/sbin:/usr/local/bin:/usr/bin"

TPecho "Generating fstab"
genfstab -U -p /mnt > /mnt/etc/fstab 2>> feliz.log
if [ ${SwapFile} ]; then
  TPecho "Making /swapfile"
  fallocate -l ${SwapFile} /mnt/swapfile >/dev/null 2>> feliz.log
  chmod 600 /mnt/swapfile >/dev/null 2>> feliz.log
  mkswap /mnt/swapfile >/dev/null 2>> feliz.log
  swapon /mnt/swapfile >/dev/null 2>> feliz.log
  echo "/swapfile none  swap  defaults  0 0" >> /mnt/etc/fstab
fi

TPecho "Setting hostname"
echo ${HostName} > /mnt/etc/hostname 2>> feliz.log
sed -i "/127.0.0.1/s/$/ ${HostName}/" /mnt/etc/hosts 2>> feliz.log
sed -i "/::1/s/$/ ${HostName}/" /mnt/etc/hosts 2>> feliz.log

# Set up locale, etc
TPecho "Preparing locale.gen"
echo "${CountryLocale} UTF-8" > /mnt/etc/locale.gen 2>> feliz.log # eg: en_US.UTF-8 UTF-8
arch_chroot "locale-gen"
TPecho "Preparing locale.conf"
echo "LANG=${CountryLocale}" > /mnt/etc/locale.conf 2>> feliz.log # eg: LANG=en_US.UTF-8
export "LANG=${CountryLocale}" 2>> feliz.log # eg: LANG=en_US.UTF-8
TPecho "Setting clock"
arch_chroot "ln -sf /usr/share/zoneinfo/${ZONE}/${SUBZONE} /etc/localtime"
arch_chroot "hwclock --systohc --utc"

if [ $Scope != "Basic" ]; then
  TPecho "Enabling dhcpcd"
  arch_chroot "systemctl enable dhcpcd.service"
  TPecho "Installing and configuring network services"
  pacstrap /mnt networkmanager network-manager-applet rp-pppoe 2>> feliz.log
  arch_chroot "systemctl enable NetworkManager.service && systemctl enable NetworkManager-dispatcher.service"
fi

if [ ${GrubDevice} ]; then
  TPecho "Installing Grub to $GrubDevice"
  pacstrap /mnt grub 2>> feliz.log
  if [ $OSprober = "Y" ]; then
    pacstrap /mnt os-prober 2>> feliz.log
  fi
  arch_chroot "grub-install --target=i386-pc --recheck ${GrubDevice}"
  arch_chroot "grub-mkconfig -o /boot/grub/grub.cfg"
else
  TPecho "Not installing Grub" >> feliz.log
fi

TPecho "Running mkinitcpio}"
if [ $Kernel = "1" ]; then
  arch_chroot "mkinitcpio -p linux-lts"
else
  arch_chroot "mkinitcpio -p linux"
fi

# Set keyboard to selected language at next startup
echo KEYMAP=${Countrykbd} > /mnt/etc/vconsole.conf 2>> feliz.log

# Extra processes for desktop installation
if [ $Scope != "Basic" ]; then
  # Various bits
  TPecho "Adding codecs"
  pacstrap /mnt a52dec autofs faac faad2 flac lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 gstreamer0.10-plugins pulseaudio pulseaudio-alsa libdvdcss libdvdread libdvdnav dvd+rw-tools dvdauthor dvgrab flashplugin 2>> feliz.log
  TPecho "Installing Wireless Tools"
  pacstrap /mnt b43-fwcutter ipw2100-fw ipw2200-fw zd1211-firmware 2>> feliz.log
  pacstrap /mnt iw wireless_tools wpa_actiond dialog wifi-menu 2>> feliz.log
  TPecho "Installing X, Graphics, etc"
  pacstrap /mnt xorg-server-utils xorg-xinit xorg-twm 2>> feliz.log
  pacstrap /mnt xf86-input-synaptics 2>> feliz.log
  pacstrap /mnt gvfs gamin 2>> feliz.log

  # Install desktop environments, window managers and display managers
  InstallLuxuries # common/shared
  #
  UserAdd
fi

EndTime=$(date +%s)
Difference=$(( $EndTime-$StartTime ))
DIFFMIN=$(( $Difference/60 ))
DIFFSEC=$(( $Difference % 60 ))

SetRootPassword
if [ $Scope != "Basic" ]; then
  SetUserPassword
fi
cp feliz.log /mnt/etc # Copy installation log for reference
print_heading
read_timed "Congratulations, installation is complete."
read_timed "It is time to restart the computer into"
read_timed "your new system. Have fun with Arch Linux."
shutdown now
