#!/bin/bash
  
testbed() {

#
PrintOne "Testing - just a longish line of text"
      
}

# ~~~~~~~
# Execute
# ~~~~~~~
  
# First check for external functions and variables files
if [[ -f `pwd`/shared ]]; then
  source shared
else
  echo "missing file: shared"
  exit 1
fi
if [[ -f `pwd`/various ]]; then
  source various
else
  echo "missing file: various"
  exit 1
fi
if [[ -f `pwd`/partitioning ]]; then
  source partitioning
else
  echo "missing file: partitioning"
  exit 1
fi
if [[ -f `pwd`/desktop ]]; then
  source desktop
else
  echo "missing file: desktop"
  exit 1
fi
if [[ -f `pwd`/listgen ]]; then
  source listgen
else
  echo "missing file: listgen"
  exit 1
fi
  
  # Various variables
  UEFI=0
#  RootPartition="sda10"
#  RootType="ext4"
#  SwapPartition="sda7"
#  PartitionList="sda2 sda3"
#  AddPartList[0]="sda9"
#  AddPartLabel[0]="/home"
#  AddPartType[0]="ext4"
#  AddPartList[1]="sda5"
#  AddPartLabel[1]="/spare"
#  AddPartType[1]="ext4"
#  GrubDevice="/dev/sda"
#  CountryCode="GB"
#  CountryLocale="en_GB.UTF-8"
#  Countrykbd="uk"
#  ZONE="Europe"
#  SUBZONE="London"
#  DesktopEnvironment="xfce4"
#  DisplayManager="lightdm"
#  Greeter="lightdm-gtk-greeter"
#  LuxuriesList="firefox libreoffice-still geany pamac-aur"
#  HostName="ArchLinux"
#  RootPassword="Root"
#  UserName="archie"
#  UserPassword="Linux"
#  DesktopEnvironment="Gnome"
  
  # Call the function 'testbed' holding code to be tested
  testbed
  echo $* # Add any variables needed for viewing before exit
  echo "End of test"
  
  exit
  
  # Code for checking arrays
  Counter=0
  for i in ${AddPartList[@]}	
  do
    echo ${AddPartList[$Counter]}
    echo ${AddPartLabel[$Counter]} 
    echo ${AddPartType[$Counter]}
    Counter=$((Counter+1))
  done
  
