#!/bin/bash

# The Feliz installation scripts for Arch Linux
# 19 April 2016

# /squiff/listgen - Semi-graphical Dialog interface
# Menuing functions - listgen1 and listgen2

# Developed by Elizabeth Mills

# Please read the introduction in the README file

# Both functions prepare the array Options[@] for display in a Dialog menu

declare -a Options  # For caller

listgen1() {
  Counter=0
  Options=() # Empty the array
  # Prepare $1 for dialog menu
  for item in $1 # Prepare string array of list items passed as $1
  do
    Counter=$((Counter+1))
    Options[${Counter}]="$item"
    Counter=$((Counter+1))
    Options[${Counter}]="-"
  done
}

listgen2() {
  Options=() # Empty the array
  Counter=0
  for item in $1; do
    Items[${Counter}]=$item
    Counter=$((Counter+1))
  done
  Counter=0
  local ItemCounter=0
  # Import the complex array
  name=$2[@]
  LongName=("${!name}")
  # Combine for dialog menu
  for item in "${LongName[@]}"; do
    Options[$((Counter))]="${Items[${ItemCounter}]}"
    Options[$((Counter+1))]="$item"
    Counter=$((Counter+2))
    ItemCounter=$((ItemCounter+1))
  done
}
