#!/bin/bash

# listgen - Dialog version of menu functions used throughout Feliz
# Adapted by Elizabeth Mills from the cli version to use Dialog

# Both functions return the selected item as text using global variable $Result
# and errorcode as $Response (to remain consistent with the cli version as far as possible)
# Window width and height are adjusted according to content

# listgen1 receives three parameters:
# 1) Primary file (string of single-word references)
# 2) Optional one-word --title
# 3) Optional hiding of <Cancel> ("nocancel")

# listgen2 has extended descriptions using the name of the complex array
# Passed as 4th parameter:

# Global variable $Passed may be used as --backtitle

declare -a Options  # For caller

listgen1() {
  Counter=0
  Options=() # Empty the array
  # Prepare $1 for dialog menu
  for item in $1 # Prepare string array of list items passed as $1
  do
    Counter=$((Counter+1))
    Options[${Counter}]="$item"
    Counter=$((Counter+1))
    Options[${Counter}]="-"
  done
}

listgen2() {
  Options=() # Empty the array
  Counter=0
  for item in $1; do
    Items[${Counter}]=$item
    Counter=$((Counter+1))
  done
  Counter=0
  local ItemCounter=0
  # Import the complex array
  name=$2[@]
  LongName=("${!name}")
  # Combine for dialog menu
  for item in "${LongName[@]}"; do
    Options[$((Counter))]="${Items[${ItemCounter}]}"
    Options[$((Counter+1))]="$item"
    Counter=$((Counter+2))
    ItemCounter=$((ItemCounter+1))
  done
}
